services:
  - type: web
    name: doccano-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings.production"
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ADMIN_EMAIL
        value: "admin@example.com"
      - key: ALLOWED_GMAIL_DOMAINS
        value: "gmail.com"
      - key: PORT
        value: "8000"
      - key: WORKERS
        value: "2"
      - key: CELERY_WORKERS
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: doccano-db
          property: connectionString

databases:
  - name: doccano-db
    plan: free
    databaseName: doccano
    user: doccano

